// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5A1XHF-O4pJbtPu2bl7x2UyrdPgzYlWg',
    appId: '1:452949743403:web:e955f597ace03821bc576e',
    messagingSenderId: '452949743403',
    projectId: 'joytop-1',
    authDomain: 'joytop-1.firebaseapp.com',
    storageBucket: 'joytop-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzW8fb6GXTWlbGWmeIyeH-SuQsNgR9g_w',
    appId: '1:452949743403:android:d72251b7c9fd4591bc576e',
    messagingSenderId: '452949743403',
    projectId: 'joytop-1',
    storageBucket: 'joytop-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChXLxh2zXIr8hZmPROosPORFRtKGTl6kk',
    appId: '1:452949743403:ios:338c4a368d30dcdabc576e',
    messagingSenderId: '452949743403',
    projectId: 'joytop-1',
    storageBucket: 'joytop-1.appspot.com',
    iosBundleId: 'com.example.joyTop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChXLxh2zXIr8hZmPROosPORFRtKGTl6kk',
    appId: '1:452949743403:ios:338c4a368d30dcdabc576e',
    messagingSenderId: '452949743403',
    projectId: 'joytop-1',
    storageBucket: 'joytop-1.appspot.com',
    iosBundleId: 'com.example.joyTop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5A1XHF-O4pJbtPu2bl7x2UyrdPgzYlWg',
    appId: '1:452949743403:web:19a347bf377d723bbc576e',
    messagingSenderId: '452949743403',
    projectId: 'joytop-1',
    authDomain: 'joytop-1.firebaseapp.com',
    storageBucket: 'joytop-1.appspot.com',
  );
}
